# Generated by Django 4.0.2 on 2022-03-03 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_firstLogin',
        ),
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='Suspended'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Last Active'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
    ]
