# Generated by Django 4.0.2 on 2022-03-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_remove_account_is_firstlogin_account_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
