# Generated by Django 4.0.2 on 2022-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_name_student_first_name_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone_no',
            field=models.CharField(default='2547xxxxxxx', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
