# Generated by Django 4.0.2 on 2022-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_parent_name_student_parent_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
