# Generated by Django 3.2.7 on 2022-03-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='billy', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
