# Generated by Django 3.2.7 on 2022-03-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20220311_1012'),
        ('student', '0005_auto_20220311_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(blank=True, to='curriculum.Subject'),
        ),
    ]
