# Generated by Django 3.2.7 on 2022-03-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_auto_20220311_1118'),
        ('student', '0006_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.class')),
            ],
        ),
    ]
