# Generated by Django 4.0.2 on 2022-03-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_remove_subject_curriculum_subject_code_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='descrption',
        ),
    ]
