# Generated by Django 3.2.7 on 2022-03-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_remove_subject_descrption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('link', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='resource',
            field=models.ManyToManyField(blank=True, to='curriculum.Resource'),
        ),
    ]
