# Generated by Django 3.2.7 on 2022-03-11 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20220311_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
