# Generated by Django 3.2.7 on 2022-03-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20220311_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='link',
        ),
    ]
