# Generated by Django 3.2.7 on 2022-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_assignment_studentannouncement_teacherannouncement_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
