# Generated by Django 3.2.7 on 2022-03-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_assignment_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
